### ISSUE TITLE
pypidb

### ISSUE THREAD

**Issue by jayvdb** [jwodder/qypi#3]
Hi, you might be interested in integrating https://github.com/jayvdb/pypidb to obtain more reliable links.  You can see a sample of the links it does resolve at https://github.com/jayvdb/pypidb/blob/master/tests/data.py , and also a list of the ones it cant resolve in `bad_metadata`.

I am very keen to add more post processing of the pypi metadata, which I see you are also doing, but my focus is on information which can only sensibly be obtained by analysing multiple pypi metadata records and following links that they contain to obtain or verify information.

**Comment by jwodder** [comment]
qypi's post-processing of metadata is limited to just making things a little more organized.  Digging into links like pypidb does is a bit more heavy-duty than I'd like, so I'm going to pass on the integration.  Thanks for the suggestion, though!
